2025-08-10 16:44:39,614 INFO    StreamThr :56944 [internal.py:wandb_internal():88] W&B internal server running at pid: 56944, started at: 2025-08-10 16:44:39.613175
2025-08-10 16:44:39,617 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: status
2025-08-10 16:44:39,784 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: status
2025-08-10 16:44:39,787 DEBUG   SenderThread:56944 [sender.py:send():303] send: header
2025-08-10 16:44:39,787 INFO    WriterThread:56944 [datastore.py:open_for_write():75] open: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/run-i9krn3d5.wandb
2025-08-10 16:44:47,425 DEBUG   SenderThread:56944 [sender.py:send():303] send: run
2025-08-10 16:44:47,661 INFO    SenderThread:56944 [dir_watcher.py:__init__():216] watching files in: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/files
2025-08-10 16:44:47,662 INFO    SenderThread:56944 [sender.py:_start_run_threads():928] run started: i9krn3d5 with start time 1754869479.607261
2025-08-10 16:44:47,662 DEBUG   SenderThread:56944 [sender.py:send():303] send: summary
2025-08-10 16:44:47,662 INFO    SenderThread:56944 [sender.py:_save_file():1171] saving file wandb-summary.json with policy end
2025-08-10 16:44:47,684 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: check_version
2025-08-10 16:44:47,685 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: check_version
2025-08-10 16:44:47,757 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: run_start
2025-08-10 16:44:47,780 DEBUG   HandlerThread:56944 [meta.py:__init__():34] meta init
2025-08-10 16:44:47,780 DEBUG   HandlerThread:56944 [meta.py:__init__():49] meta init done
2025-08-10 16:44:47,780 DEBUG   HandlerThread:56944 [meta.py:probe():215] probe
2025-08-10 16:44:47,800 DEBUG   HandlerThread:56944 [meta.py:_setup_git():205] setup git
2025-08-10 16:44:47,826 DEBUG   HandlerThread:56944 [meta.py:_setup_git():212] setup git done
2025-08-10 16:44:47,826 DEBUG   HandlerThread:56944 [meta.py:_save_pip():53] save pip
2025-08-10 16:44:47,827 DEBUG   HandlerThread:56944 [meta.py:_save_pip():67] save pip done
2025-08-10 16:44:47,827 DEBUG   HandlerThread:56944 [meta.py:probe():253] probe done
2025-08-10 16:44:47,869 DEBUG   SenderThread:56944 [sender.py:send():303] send: files
2025-08-10 16:44:47,870 INFO    SenderThread:56944 [sender.py:_save_file():1171] saving file wandb-metadata.json with policy now
2025-08-10 16:44:47,889 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:44:47,890 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:44:47,992 DEBUG   SenderThread:56944 [sender.py:send():303] send: telemetry
2025-08-10 16:44:48,280 INFO    Thread-17 :56944 [upload_job.py:push():143] Uploaded file /tmp/tmpdyqh0mlnwandb/2n0546t7-wandb-metadata.json
2025-08-10 16:44:48,665 INFO    Thread-13 :56944 [dir_watcher.py:_on_file_created():275] file/dir created: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/files/wandb-summary.json
2025-08-10 16:44:48,666 INFO    Thread-13 :56944 [dir_watcher.py:_on_file_created():275] file/dir created: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/files/requirements.txt
2025-08-10 16:44:48,666 INFO    Thread-13 :56944 [dir_watcher.py:_on_file_created():275] file/dir created: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/files/wandb-metadata.json
2025-08-10 16:45:05,966 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:45:05,967 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:45:11,674 INFO    Thread-13 :56944 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/files/config.yaml
2025-08-10 16:45:20,931 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:45:27,282 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:45:27,283 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:45:48,691 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:45:48,692 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:45:55,871 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:46:10,047 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:46:10,047 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:46:31,008 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:46:31,658 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:46:31,659 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:46:56,543 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:47:21,540 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:47:40,239 ERROR   SenderThread:56944 [retry.py:__call__():154] Retry attempt failed:
Traceback (most recent call last):
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/util/connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/miniconda3/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f8fae932e80>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fae932e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/wandb/sdk/lib/retry.py", line 113, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/wandb/sdk/internal/internal_api.py", line 213, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 38, in execute
    request = requests.post(self.url, **post_args)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/mmendieta/transformers/lib/python3.8/site-packages/requests/adapters.py", line 700, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f8fae932e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2025-08-10 16:47:46,592 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:48:11,596 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:48:31,597 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:48:51,598 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:49:11,599 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:49:31,600 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:49:51,601 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:50:11,602 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:50:31,603 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:50:51,604 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:51:11,605 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:51:19,821 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:19,977 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:51:19,979 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:20,120 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:51:20,125 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:20,241 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:20,433 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:51:20,435 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:20,639 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:20,784 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:51:20,787 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:20,878 INFO    Thread-13 :56944 [dir_watcher.py:_on_file_created():275] file/dir created: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/files/output.log
2025-08-10 16:51:20,954 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:51:20,956 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:21,061 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:21,237 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:51:21,240 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:21,403 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:21,589 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:51:21,591 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:21,769 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:21,963 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:51:22,879 INFO    Thread-13 :56944 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/files/output.log
2025-08-10 16:51:31,606 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:51:31,606 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:46,800 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:51:46,800 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:51:58,332 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:52:01,978 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:52:01,978 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:52:17,141 DEBUG   HandlerThread:56944 [handler.py:handle_request():138] handle_request: stop_status
2025-08-10 16:52:17,141 DEBUG   SenderThread:56944 [sender.py:send_request():317] send_request: stop_status
2025-08-10 16:52:26,917 INFO    Thread-13 :56944 [dir_watcher.py:_on_file_modified():292] file/dir modified: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/files/output.log
2025-08-10 16:52:35,621 DEBUG   SenderThread:56944 [sender.py:send():303] send: stats
2025-08-10 16:52:41,163 WARNING StreamThr :56944 [internal.py:is_dead():385] Internal process exiting, parent pid 53592 disappeared
2025-08-10 16:52:41,164 ERROR   StreamThr :56944 [internal.py:wandb_internal():147] Internal process shutdown.
2025-08-10 16:52:41,623 INFO    WriterThread:56944 [datastore.py:close():279] close: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250810_164439-i9krn3d5/run-i9krn3d5.wandb
2025-08-10 16:52:41,624 INFO    SenderThread:56944 [sender.py:finish():1331] shutting down sender
2025-08-10 16:52:41,628 INFO    HandlerThread:56944 [handler.py:finish():814] shutting down handler
2025-08-10 16:52:41,915 INFO    MainThread:56944 [internal.py:handle_exit():78] Internal process exited
2025-08-10 16:52:41,916 WARNING MsgRouterThr:56944 [router.py:message_loop():74] EOFError seen in message_loop
